// Predefined fixed demo datasets for all 5 social media platforms
// Contains consistent profile metrics and content items

export const demoData = {
  youtube: {
    account: {
      name: "DevByte Tutorials",
      handle: "@devbyte",
      avatarUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150",
      bannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800",
      followersCount: 154200,
      followingCount: null,
      contentCount: 5,
      totalViews: 381000,
      description: "DevByte is your daily dose of development tutorials, programming tips, and coding deep dives.",
      country: "United States",
      accountType: "channel",
      externalUrl: "https://youtube.com/c/devbyte",
    },
    content: [
      {
        id: "yt_video_1",
        title: "How to Build Fullstack Apps in 2026",
        type: "video",
        thumbnailUrl: "https://images.unsplash.com/photo-1618401471353-b98aedd07871?w=300",
        url: "https://www.youtube.com/watch?v=demo1",
        publishedAt: "2026-08-10T14:30:00Z",
        metrics: {
          views: 45000,
          likes: 3200,
          comments: 410,
          shares: 180,
          saves: 1250,
          duration: 5400,
        },
      },
      {
        id: "yt_video_2",
        title: "FastAPI + React Complete Masterclass",
        type: "video",
        thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=300",
        url: "https://www.youtube.com/watch?v=demo2",
        publishedAt: "2026-08-05T09:00:00Z",
        metrics: {
          views: 82000,
          likes: 6400,
          comments: 890,
          shares: 420,
          saves: 2400,
          duration: 11200,
        },
      },
      {
        id: "yt_video_3",
        title: "5 AI Tools You Must Use Everyday",
        type: "short",
        thumbnailUrl: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=300",
        url: "https://www.youtube.com/shorts/demo3",
        publishedAt: "2026-08-01T17:15:00Z",
        metrics: {
          views: 125000,
          likes: 14200,
          comments: 1100,
          shares: 1850,
          saves: 450,
          duration: 45,
        },
      },
      {
        id: "yt_video_4",
        title: "Behind the Scenes of My Creator Business",
        type: "video",
        thumbnailUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=300",
        url: "https://www.youtube.com/watch?v=demo4",
        publishedAt: "2026-07-25T11:00:00Z",
        metrics: {
          views: 31000,
          likes: 2100,
          comments: 320,
          shares: 95,
          saves: 780,
          duration: 3800,
        },
      },
      {
        id: "yt_video_5",
        title: "10 Mins Coding Challenge with Python",
        type: "short",
        thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=300",
        url: "https://www.youtube.com/shorts/demo5",
        publishedAt: "2026-07-20T10:00:00Z",
        metrics: {
          views: 98000,
          likes: 9800,
          comments: 750,
          shares: 1200,
          saves: 310,
          duration: 55,
        },
      },
    ],
    // YouTube audience dataset — shaped like a mega-creator channel (MrBeast-style):
    // young, male-skewed, US + India heavy, mobile-first.
    audience: {
      overview: {
        totalFollowers: 154200,
        newFollowers: 3850,
        monthlyFollowerGrowth: 2.6,
        reach: 412000,
        impressions: 1180000,
        avgEngagementRate: 4.1,
      },
      demographics: {
        age: [
          { range: '18-24', percentage: 38 },
          { range: '25-34', percentage: 34 },
          { range: '35-44', percentage: 15 },
          { range: '45-54', percentage: 8 },
          { range: '55+', percentage: 5 },
        ],
        gender: [
          { label: 'Male', percentage: 63 },
          { label: 'Female', percentage: 35 },
          { label: 'Other', percentage: 2 },
        ],
        countries: [
          { name: 'United States', percentage: 28, region: 'North America' },
          { name: 'India', percentage: 16, region: 'Asia' },
          { name: 'United Kingdom', percentage: 10, region: 'Europe' },
          { name: 'Brazil', percentage: 9, region: 'South America' },
          { name: 'Germany', percentage: 6, region: 'Europe' },
          { name: 'Other Countries', percentage: 31, region: 'Global' },
        ],
        regions: [
          { name: 'North America', percentage: 46 },
          { name: 'Asia', percentage: 22 },
          { name: 'Europe', percentage: 18 },
          { name: 'South America', percentage: 9 },
          { name: 'Other Regions', percentage: 5 },
        ],
        topCities: [
          { name: 'Los Angeles', country: 'United States', percentage: 5 },
          { name: 'New York', country: 'United States', percentage: 4 },
          { name: 'London', country: 'United Kingdom', percentage: 3 },
          { name: 'Mumbai', country: 'India', percentage: 3 },
          { name: 'Toronto', country: 'Canada', percentage: 2 },
        ],
      },
      followerGrowth: {
        daily: 128,
        weekly: 890,
        monthly: 3850,
        total: 154200,
        newFollowers: 3850,
        growthPercentage: 2.6,
        timeline: [
          { date: 'Mar', followers: 132400, newFollowers: 4200 },
          { date: 'Apr', followers: 136800, newFollowers: 4400 },
          { date: 'May', followers: 141900, newFollowers: 5100 },
          { date: 'Jun', followers: 146700, newFollowers: 4800 },
          { date: 'Jul', followers: 150800, newFollowers: 4100 },
          { date: 'Aug', followers: 154200, newFollowers: 3400 },
        ],
      },
      activity: {
        peakEngagementTime: 'Friday at 6:00 PM',
        mostActiveHours: [
          { hour: '6:00 PM', activity: 92 },
          { hour: '7:00 PM', activity: 88 },
          { hour: '8:00 PM', activity: 84 },
          { hour: '5:00 PM', activity: 78 },
          { hour: '9:00 PM', activity: 71 },
        ],
        mostActiveDays: [
          { day: 'Friday', percentage: 18 },
          { day: 'Saturday', percentage: 17 },
          { day: 'Thursday', percentage: 14 },
        ],
        dailyActivity: [
          { day: 'Monday', activity: 11 },
          { day: 'Tuesday', activity: 12 },
          { day: 'Wednesday', activity: 13 },
          { day: 'Thursday', activity: 14 },
          { day: 'Friday', activity: 18 },
          { day: 'Saturday', activity: 17 },
          { day: 'Sunday', activity: 15 },
        ],
      },
      devices: { mobile: 76, desktop: 17, tablet: 4, smartTv: 3 },
      geography: {
        countries: [
          { name: 'United States', type: 'Country', percentage: 28, region: 'North America' },
          { name: 'India', type: 'Country', percentage: 16, region: 'Asia' },
          { name: 'United Kingdom', type: 'Country', percentage: 10, region: 'Europe' },
          { name: 'Brazil', type: 'Country', percentage: 9, region: 'South America' },
          { name: 'Germany', type: 'Country', percentage: 6, region: 'Europe' },
          { name: 'Other Countries', type: 'Country', percentage: 31, region: 'Global' },
        ],
        regions: [
          { name: 'North America', type: 'Region', percentage: 46, region: 'North America' },
          { name: 'Asia', type: 'Region', percentage: 22, region: 'Asia' },
          { name: 'Europe', type: 'Region', percentage: 18, region: 'Europe' },
          { name: 'South America', type: 'Region', percentage: 9, region: 'South America' },
          { name: 'Other Regions', type: 'Region', percentage: 5, region: 'Global' },
        ],
        topCities: [
          { name: 'Los Angeles', type: 'City', percentage: 5, region: 'United States' },
          { name: 'New York', type: 'City', percentage: 4, region: 'United States' },
          { name: 'London', type: 'City', percentage: 3, region: 'United Kingdom' },
          { name: 'Mumbai', type: 'City', percentage: 3, region: 'India' },
          { name: 'Toronto', type: 'City', percentage: 2, region: 'Canada' },
        ],
      },
      reach: {
        totalReach: 412000,
        totalImpressions: 1180000,
        uniqueViewers: 206000,
        reachTrend: [
          { date: 'Mar', reach: 312000 },
          { date: 'Apr', reach: 336000 },
          { date: 'May', reach: 351000 },
          { date: 'Jun', reach: 372000 },
          { date: 'Jul', reach: 391000 },
          { date: 'Aug', reach: 412000 },
        ],
        impressionTrend: [
          { date: 'Mar', impressions: 940000 },
          { date: 'Apr', impressions: 1010000 },
          { date: 'May', impressions: 1050000 },
          { date: 'Jun', impressions: 1100000 },
          { date: 'Jul', impressions: 1145000 },
          { date: 'Aug', impressions: 1180000 },
        ],
      },
      engagement: {
        totalLikes: 35700,
        totalComments: 3470,
        shares: 3745,
        saves: 5190,
        engagementRate: 4.1,
        trends: [
          { date: 'Mar', likes: 21000, comments: 1900, shares: 2100, saves: 2900 },
          { date: 'Apr', likes: 25400, comments: 2300, shares: 2600, saves: 3400 },
          { date: 'May', likes: 28900, comments: 2700, shares: 2900, saves: 3900 },
          { date: 'Jun', likes: 31200, comments: 3000, shares: 3200, saves: 4300 },
          { date: 'Jul', likes: 33900, comments: 3300, shares: 3500, saves: 4800 },
          { date: 'Aug', likes: 35700, comments: 3470, shares: 3745, saves: 5190 },
        ],
      },
    },
  },
  instagram: {
    account: {
      name: "PixelCraft Designs",
      handle: "@pixelcraft",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
      bannerUrl: null,
      followersCount: 85000,
      followingCount: 450,
      contentCount: 5,
      totalViews: 277500,
      description: "Visual tech tips, creative workspace aesthetics, and design-to-code tutorials for modern creators.",
      country: "Canada",
      accountType: "BUSINESS",
      externalUrl: "https://instagram.com/pixelcraft",
    },
    content: [
      {
        id: "ig_post_1",
        title: "Daily Tech Essentials & Workspace Setup",
        type: "reel",
        thumbnailUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300",
        url: "https://instagram.com/p/demo1",
        publishedAt: "2026-08-11T16:00:00Z",
        metrics: {
          views: 74000,
          likes: 8200,
          comments: 540,
          shares: 1300,
          saves: 380,
          duration: null,
          reach: 129000,
          watchTimeMinutes: 2100,
        },
      },
      {
        id: "ig_post_2",
        title: "Why UI Design Matters in Modern Software",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=300",
        url: "https://instagram.com/p/demo2",
        publishedAt: "2026-08-07T12:00:00Z",
        metrics: {
          views: 22000,
          likes: 3100,
          comments: 190,
          shares: 240,
          saves: 150,
          duration: null,
          reach: 47000,
          watchTimeMinutes: 640,
        },
      },
      {
        id: "ig_post_3",
        title: "React Performance Optimization Hacks",
        type: "reel",
        thumbnailUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=300",
        url: "https://instagram.com/p/demo3",
        publishedAt: "2026-08-02T18:45:00Z",
        metrics: {
          views: 110000,
          likes: 12800,
          comments: 930,
          shares: 2100,
          saves: 620,
          duration: null,
          reach: 176000,
          watchTimeMinutes: 3150,
        },
      },
      {
        id: "ig_post_4",
        title: "A Day in the Life of a Tech Influencer",
        type: "reel",
        thumbnailUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=300",
        url: "https://instagram.com/p/demo4",
        publishedAt: "2026-07-28T09:30:00Z",
        metrics: {
          views: 53000,
          likes: 6100,
          comments: 420,
          shares: 870,
          saves: 290,
          duration: null,
          reach: 92000,
          watchTimeMinutes: 1520,
        },
      },
      {
        id: "ig_post_5",
        title: "My Top 3 Creator Tools Comparison",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=300",
        url: "https://instagram.com/p/demo5",
        publishedAt: "2026-07-23T14:00:00Z",
        metrics: {
          views: 18500,
          likes: 2400,
          comments: 140,
          shares: 180,
          saves: 90,
          duration: null,
          reach: 41000,
          watchTimeMinutes: 540,
        },
      },
    ],
    // Instagram audience dataset — shaped like a visual-exploration brand (NatGeo-style):
    // slightly female-skewed, global, mobile-first, weekend-heavy engagement.
    audience: {
      overview: {
        totalFollowers: 85000,
        newFollowers: 2400,
        monthlyFollowerGrowth: 2.9,
        reach: 335000,
        impressions: 920000,
        avgEngagementRate: 4.5,
      },
      demographics: {
        age: [
          { range: '18-24', percentage: 28 },
          { range: '25-34', percentage: 36 },
          { range: '35-44', percentage: 20 },
          { range: '45-54', percentage: 11 },
          { range: '55+', percentage: 5 },
        ],
        gender: [
          { label: 'Male', percentage: 46 },
          { label: 'Female', percentage: 52 },
          { label: 'Other', percentage: 2 },
        ],
        countries: [
          { name: 'United States', percentage: 18, region: 'North America' },
          { name: 'India', percentage: 14, region: 'Asia' },
          { name: 'United Kingdom', percentage: 12, region: 'Europe' },
          { name: 'France', percentage: 9, region: 'Europe' },
          { name: 'Japan', percentage: 7, region: 'Asia' },
          { name: 'Other Countries', percentage: 40, region: 'Global' },
        ],
        regions: [
          { name: 'North America', percentage: 24 },
          { name: 'Asia', percentage: 23 },
          { name: 'Europe', percentage: 27 },
          { name: 'South America', percentage: 9 },
          { name: 'Other Regions', percentage: 17 },
        ],
        topCities: [
          { name: 'New York', country: 'United States', percentage: 4 },
          { name: 'London', country: 'United Kingdom', percentage: 3 },
          { name: 'Tokyo', country: 'Japan', percentage: 3 },
          { name: 'Mumbai', country: 'India', percentage: 3 },
          { name: 'Paris', country: 'France', percentage: 3 },
        ],
      },
      followerGrowth: {
        daily: 80,
        weekly: 560,
        monthly: 2400,
        total: 85000,
        newFollowers: 2400,
        growthPercentage: 2.9,
        timeline: [
          { date: 'Mar', followers: 71000, newFollowers: 2600 },
          { date: 'Apr', followers: 73800, newFollowers: 2800 },
          { date: 'May', followers: 76200, newFollowers: 2400 },
          { date: 'Jun', followers: 78800, newFollowers: 2600 },
        { date: 'Jul', followers: 81600, newFollowers: 2800 },
        { date: 'Aug', followers: 85000, newFollowers: 3400 },
        ],
      },
      activity: {
        peakEngagementTime: 'Sunday at 8:00 PM',
        mostActiveHours: [
          { hour: '8:00 PM', activity: 94 },
          { hour: '7:00 PM', activity: 90 },
          { hour: '9:00 PM', activity: 86 },
          { hour: '6:00 PM', activity: 80 },
          { hour: '12:00 PM', activity: 74 },
        ],
        mostActiveDays: [
          { day: 'Sunday', percentage: 20 },
          { day: 'Saturday', percentage: 18 },
          { day: 'Friday', percentage: 14 },
        ],
        dailyActivity: [
          { day: 'Monday', activity: 12 },
          { day: 'Tuesday', activity: 11 },
          { day: 'Wednesday', activity: 13 },
          { day: 'Thursday', activity: 12 },
          { day: 'Friday', activity: 14 },
          { day: 'Saturday', activity: 18 },
          { day: 'Sunday', activity: 20 },
        ],
      },
      devices: { mobile: 88, desktop: 8, tablet: 3, smartTv: 1 },
      geography: {
        countries: [
          { name: 'United States', type: 'Country', percentage: 18, region: 'North America' },
          { name: 'India', type: 'Country', percentage: 14, region: 'Asia' },
          { name: 'United Kingdom', type: 'Country', percentage: 12, region: 'Europe' },
          { name: 'France', type: 'Country', percentage: 9, region: 'Europe' },
          { name: 'Japan', type: 'Country', percentage: 7, region: 'Asia' },
          { name: 'Other Countries', type: 'Country', percentage: 40, region: 'Global' },
        ],
        regions: [
          { name: 'North America', type: 'Region', percentage: 24, region: 'North America' },
          { name: 'Asia', type: 'Region', percentage: 23, region: 'Asia' },
          { name: 'Europe', type: 'Region', percentage: 27, region: 'Europe' },
          { name: 'South America', type: 'Region', percentage: 9, region: 'South America' },
          { name: 'Other Regions', type: 'Region', percentage: 17, region: 'Global' },
        ],
        topCities: [
          { name: 'New York', type: 'City', percentage: 4, region: 'United States' },
          { name: 'London', type: 'City', percentage: 3, region: 'United Kingdom' },
          { name: 'Tokyo', type: 'City', percentage: 3, region: 'Japan' },
          { name: 'Mumbai', type: 'City', percentage: 3, region: 'India' },
          { name: 'Paris', type: 'City', percentage: 3, region: 'France' },
        ],
      },
      reach: {
        totalReach: 335000,
        totalImpressions: 920000,
        uniqueViewers: 186000,
        reachTrend: [
          { date: 'Mar', reach: 262000 },
          { date: 'Apr', reach: 281000 },
          { date: 'May', reach: 296000 },
          { date: 'Jun', reach: 308000 },
          { date: 'Jul', reach: 322000 },
          { date: 'Aug', reach: 335000 },
        ],
        impressionTrend: [
          { date: 'Mar', impressions: 720000 },
          { date: 'Apr', impressions: 780000 },
          { date: 'May', impressions: 820000 },
          { date: 'Jun', impressions: 850000 },
          { date: 'Jul', impressions: 880000 },
          { date: 'Aug', impressions: 920000 },
        ],
        watchTimeTrend: [
          { date: 'Mar', minutes: 64000 },
          { date: 'Apr', minutes: 71000 },
          { date: 'May', minutes: 77000 },
          { date: 'Jun', minutes: 82000 },
          { date: 'Jul', minutes: 86000 },
          { date: 'Aug', minutes: 90000 },
        ],
      },
      engagement: {
        totalLikes: 32600,
        totalComments: 2220,
        shares: 4690,
        saves: 1530,
        engagementRate: 4.5,
        trends: [
          { date: 'Mar', likes: 19800, comments: 1320, shares: 2910, saves: 940 },
          { date: 'Apr', likes: 23200, comments: 1580, shares: 3480, saves: 1120 },
          { date: 'May', likes: 26100, comments: 1760, shares: 3860, saves: 1240 },
          { date: 'Jun', likes: 28900, comments: 1980, shares: 4250, saves: 1380 },
          { date: 'Jul', likes: 31200, comments: 2140, shares: 4520, saves: 1480 },
          { date: 'Aug', likes: 32600, comments: 2220, shares: 4690, saves: 1530 },
        ],
      },
    },
  },
  facebook: {
    account: {
      name: "CreatorIQ Page",
      handle: "@creatoriq_page",
      avatarUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=150",
      bannerUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800",
      followersCount: 42000,
      followingCount: null,
      contentCount: 5,
      totalViews: 89000,
      description: "CreatorIQ is the official community hub for content operations tips, algorithm breakdowns, and growth playbooks.",
      country: "United States",
      accountType: "PAGE",
      externalUrl: "https://facebook.com/creatoriq_page",
    },
    content: [
      {
        id: "fb_post_1",
        title: "Creator Growth Blueprint 2026",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=300",
        url: "https://facebook.com/posts/demo1",
        publishedAt: "2026-08-12T10:00:00Z",
        metrics: {
          views: 14500,
          likes: 1200,
          comments: 95,
          shares: 110,
          saves: 68,
          duration: null,
          reach: 23500,
          watchTimeMinutes: 480,
        },
      },
      {
        id: "fb_post_2",
        title: "Live Q&A: Social Media Algorithms Explained",
        type: "video",
        thumbnailUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=300",
        url: "https://facebook.com/posts/demo2",
        publishedAt: "2026-08-08T15:00:00Z",
        metrics: {
          views: 38000,
          likes: 3400,
          comments: 410,
          shares: 320,
          saves: 190,
          duration: 4200,
          reach: 61000,
          watchTimeMinutes: 3100,
        },
      },
      {
        id: "fb_post_3",
        title: "5 Posting Frequency Myths Debunked",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=300",
        url: "https://facebook.com/posts/demo3",
        publishedAt: "2026-08-04T12:30:00Z",
        metrics: {
          views: 8200,
          likes: 640,
          comments: 58,
          shares: 74,
          saves: 41,
          duration: null,
          reach: 16200,
          watchTimeMinutes: 310,
        },
      },
      {
        id: "fb_post_4",
        title: "How We Grew a Page from 0 to 10K in 90 Days",
        type: "video",
        thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300",
        url: "https://facebook.com/posts/demo4",
        publishedAt: "2026-07-28T09:45:00Z",
        metrics: {
          views: 21400,
          likes: 1900,
          comments: 230,
          shares: 185,
          saves: 122,
          duration: 7800,
          reach: 39800,
          watchTimeMinutes: 2100,
        },
      },
      {
        id: "fb_post_5",
        title: "Community Spotlight: Top Member Creations",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=300",
        url: "https://facebook.com/posts/demo5",
        publishedAt: "2026-07-21T16:20:00Z",
        metrics: {
          views: 6900,
          likes: 480,
          comments: 120,
          shares: 42,
          saves: 29,
          duration: null,
          reach: 14500,
          watchTimeMinutes: 240,
        },
      },
    ],
    // Facebook audience dataset — shaped like a legacy page persona (NatGeo-style):
    // older, balanced audience, heavy desktop+tablet usage, weekday engagement.
    audience: {
      overview: {
        totalFollowers: 42000,
        newFollowers: 1250,
        monthlyFollowerGrowth: 3.1,
        reach: 142000,
        impressions: 310000,
        avgEngagementRate: 3.2,
      },
      demographics: {
        age: [
          { range: '18-24', percentage: 12 },
          { range: '25-34', percentage: 24 },
          { range: '35-44', percentage: 26 },
          { range: '45-54', percentage: 22 },
          { range: '55+', percentage: 16 },
        ],
        gender: [
          { label: 'Male', percentage: 45 },
          { label: 'Female', percentage: 53 },
          { label: 'Other', percentage: 2 },
        ],
        countries: [
          { name: 'United States', percentage: 34, region: 'North America' },
          { name: 'India', percentage: 12, region: 'Asia' },
          { name: 'United Kingdom', percentage: 9, region: 'Europe' },
          { name: 'Canada', percentage: 7, region: 'North America' },
          { name: 'Australia', percentage: 5, region: 'Oceania' },
          { name: 'Other Countries', percentage: 33, region: 'Global' },
        ],
        regions: [
          { name: 'North America', percentage: 44 },
          { name: 'Europe', percentage: 21 },
          { name: 'Asia', percentage: 16 },
          { name: 'Oceania', percentage: 8 },
          { name: 'Other Regions', percentage: 11 },
        ],
        topCities: [
          { name: 'New York', country: 'United States', percentage: 5 },
          { name: 'Los Angeles', country: 'United States', percentage: 4 },
          { name: 'Chicago', country: 'United States', percentage: 3 },
          { name: 'London', country: 'United Kingdom', percentage: 3 },
          { name: 'Toronto', country: 'Canada', percentage: 3 },
        ],
      },
      followerGrowth: {
        daily: 42,
        weekly: 290,
        monthly: 1250,
        total: 42000,
        newFollowers: 1250,
        growthPercentage: 3.1,
        timeline: [
          { date: 'Mar', followers: 34500, newFollowers: 1100 },
          { date: 'Apr', followers: 35800, newFollowers: 1300 },
          { date: 'May', followers: 37100, newFollowers: 1300 },
          { date: 'Jun', followers: 38300, newFollowers: 1200 },
          { date: 'Jul', followers: 39800, newFollowers: 1500 },
          { date: 'Aug', followers: 42000, newFollowers: 2200 },
        ],
      },
      activity: {
        peakEngagementTime: 'Thursday at 7:00 PM',
        mostActiveHours: [
          { hour: '7:00 PM', activity: 90 },
          { hour: '8:00 PM', activity: 86 },
          { hour: '6:00 PM', activity: 82 },
          { hour: '9:00 PM', activity: 76 },
          { hour: '12:00 PM', activity: 70 },
        ],
        mostActiveDays: [
          { day: 'Thursday', percentage: 16 },
          { day: 'Wednesday', percentage: 14 },
          { day: 'Monday', percentage: 14 },
        ],
        dailyActivity: [
          { day: 'Monday', activity: 14 },
          { day: 'Tuesday', activity: 13 },
          { day: 'Wednesday', activity: 14 },
          { day: 'Thursday', activity: 16 },
          { day: 'Friday', activity: 15 },
          { day: 'Saturday', activity: 15 },
          { day: 'Sunday', activity: 13 },
        ],
      },
      devices: { mobile: 62, desktop: 22, tablet: 10, smartTv: 6 },
      geography: {
        countries: [
          { name: 'United States', type: 'Country', percentage: 34, region: 'North America' },
          { name: 'India', type: 'Country', percentage: 12, region: 'Asia' },
          { name: 'United Kingdom', type: 'Country', percentage: 9, region: 'Europe' },
          { name: 'Canada', type: 'Country', percentage: 7, region: 'North America' },
          { name: 'Australia', type: 'Country', percentage: 5, region: 'Oceania' },
          { name: 'Other Countries', type: 'Country', percentage: 33, region: 'Global' },
        ],
        regions: [
          { name: 'North America', type: 'Region', percentage: 44, region: 'North America' },
          { name: 'Europe', type: 'Region', percentage: 21, region: 'Europe' },
          { name: 'Asia', type: 'Region', percentage: 16, region: 'Asia' },
          { name: 'Oceania', type: 'Region', percentage: 8, region: 'Oceania' },
          { name: 'Other Regions', type: 'Region', percentage: 11, region: 'Global' },
        ],
        topCities: [
          { name: 'New York', type: 'City', percentage: 5, region: 'United States' },
          { name: 'Los Angeles', type: 'City', percentage: 4, region: 'United States' },
          { name: 'Chicago', type: 'City', percentage: 3, region: 'United States' },
          { name: 'London', type: 'City', percentage: 3, region: 'United Kingdom' },
          { name: 'Toronto', type: 'City', percentage: 3, region: 'Canada' },
        ],
      },
      reach: {
        totalReach: 142000,
        totalImpressions: 310000,
        uniqueViewers: 86000,
        reachTrend: [
          { date: 'Mar', reach: 108000 },
          { date: 'Apr', reach: 116000 },
          { date: 'May', reach: 123000 },
          { date: 'Jun', reach: 130000 },
          { date: 'Jul', reach: 136000 },
          { date: 'Aug', reach: 142000 },
        ],
        impressionTrend: [
          { date: 'Mar', impressions: 235000 },
          { date: 'Apr', impressions: 255000 },
          { date: 'May', impressions: 270000 },
          { date: 'Jun', impressions: 285000 },
          { date: 'Jul', impressions: 298000 },
          { date: 'Aug', impressions: 310000 },
        ],
        watchTimeTrend: [
          { date: 'Mar', minutes: 34000 },
          { date: 'Apr', minutes: 39000 },
          { date: 'May', minutes: 44000 },
          { date: 'Jun', minutes: 49000 },
          { date: 'Jul', minutes: 54000 },
          { date: 'Aug', minutes: 58000 },
        ],
      },
      engagement: {
        totalLikes: 7620,
        totalComments: 913,
        shares: 731,
        saves: 680,
        engagementRate: 3.2,
        trends: [
          { date: 'Mar', likes: 5400, comments: 680, shares: 510, saves: 420 },
          { date: 'Apr', likes: 6000, comments: 730, shares: 560, saves: 460 },
          { date: 'May', likes: 6500, comments: 780, shares: 610, saves: 520 },
          { date: 'Jun', likes: 7000, comments: 830, shares: 660, saves: 570 },
          { date: 'Jul', likes: 7350, comments: 880, shares: 700, saves: 630 },
          { date: 'Aug', likes: 7620, comments: 913, shares: 731, saves: 680 },
        ],
      },
    },
  },
  linkedin: {
    account: {
      name: "Enterprise Creators",
      handle: "@enterprise_creators",
      avatarUrl: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=150",
      bannerUrl: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800",
      followersCount: 25000,
      followingCount: null,
      contentCount: 5,
      totalViews: 97000,
      description: "Data-driven insights on corporate content operations, thought leadership, and scaling media agencies.",
      country: "United Kingdom",
      accountType: "COMPANY",
      externalUrl: "https://linkedin.com/company/enterprise_creators",
    },
    content: [
      {
        id: "li_post_1",
        title: "Building a Data-Driven Creator Enterprise",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=300",
        url: "https://linkedin.com/posts/demo1",
        publishedAt: "2026-08-13T09:15:00Z",
        metrics: {
          views: 19500,
          likes: 2100,
          comments: 280,
          shares: 450,
          saves: 340,
          duration: null,
          watchTimeMinutes: 4850,
          reach: 38000,
        },
      },
      {
        id: "li_post_2",
        title: "How We Scaled Content Operations to 1M Views",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=300",
        url: "https://linkedin.com/posts/demo2",
        publishedAt: "2026-08-09T14:00:00Z",
        metrics: {
          views: 31000,
          likes: 3600,
          comments: 490,
          shares: 710,
          saves: 520,
          duration: null,
          watchTimeMinutes: 8200,
          reach: 58000,
        },
      },
      {
        id: "li_post_3",
        title: "The Creator Economy in 2026: Key Numbers",
        type: "carousel",
        thumbnailUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=300",
        url: "https://linkedin.com/posts/demo3",
        publishedAt: "2026-08-05T10:30:00Z",
        metrics: {
          views: 24300,
          likes: 2800,
          comments: 340,
          shares: 620,
          saves: 410,
          duration: null,
          watchTimeMinutes: 6100,
          reach: 45000,
        },
      },
      {
        id: "li_post_4",
        title: "Case Study: Agency Monetization Models",
        type: "article",
        thumbnailUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=300",
        url: "https://linkedin.com/posts/demo4",
        publishedAt: "2026-07-29T13:00:00Z",
        metrics: {
          views: 12800,
          likes: 1450,
          comments: 210,
          shares: 380,
          saves: 260,
          duration: null,
          watchTimeMinutes: 3200,
          reach: 24500,
        },
      },
      {
        id: "li_post_5",
        title: "Hiring: We Are Building the Future of Creator Tech",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=300",
        url: "https://linkedin.com/posts/demo5",
        publishedAt: "2026-07-22T08:00:00Z",
        metrics: {
          views: 9400,
          likes: 980,
          comments: 160,
          shares: 290,
          saves: 180,
          duration: null,
          watchTimeMinutes: 2100,
          reach: 18000,
        },
      },
    ],
    // LinkedIn audience dataset — shaped like a professional/B2B persona (Microsoft-style):
    // career-focused, desktop-heavy, weekdays at noon.
    audience: {
      overview: {
        totalFollowers: 25000,
        newFollowers: 700,
        monthlyFollowerGrowth: 2.9,
        reach: 96000,
        impressions: 480000,
        avgEngagementRate: 3.5,
      },
      demographics: {
        age: [
          { range: '18-24', percentage: 16 },
          { range: '25-34', percentage: 32 },
          { range: '35-44', percentage: 28 },
          { range: '45-54', percentage: 16 },
          { range: '55+', percentage: 8 },
        ],
        gender: [
          { label: 'Male', percentage: 54 },
          { label: 'Female', percentage: 44 },
          { label: 'Other', percentage: 2 },
        ],
        countries: [
          { name: 'United States', percentage: 32, region: 'North America' },
          { name: 'India', percentage: 15, region: 'Asia' },
          { name: 'United Kingdom', percentage: 11, region: 'Europe' },
          { name: 'Germany', percentage: 7, region: 'Europe' },
          { name: 'Canada', percentage: 6, region: 'North America' },
          { name: 'Other Countries', percentage: 29, region: 'Global' },
        ],
        regions: [
          { name: 'North America', percentage: 41 },
          { name: 'Europe', percentage: 26 },
          { name: 'Asia', percentage: 20 },
          { name: 'Middle East', percentage: 7 },
          { name: 'Other Regions', percentage: 6 },
        ],
        topCities: [
          { name: 'New York', country: 'United States', percentage: 4 },
          { name: 'San Francisco', country: 'United States', percentage: 3 },
          { name: 'London', country: 'United Kingdom', percentage: 3 },
          { name: 'Mumbai', country: 'India', percentage: 3 },
          { name: 'Toronto', country: 'Canada', percentage: 2 },
        ],
      },
      followerGrowth: {
        daily: 23,
        weekly: 160,
        monthly: 700,
        total: 25000,
        newFollowers: 700,
        growthPercentage: 2.9,
        timeline: [
          { date: 'Mar', followers: 20800, newFollowers: 680 },
          { date: 'Apr', followers: 21600, newFollowers: 800 },
          { date: 'May', followers: 22300, newFollowers: 700 },
          { date: 'Jun', followers: 23100, newFollowers: 800 },
          { date: 'Jul', followers: 24000, newFollowers: 900 },
          { date: 'Aug', followers: 25000, newFollowers: 1000 },
        ],
      },
      activity: {
        peakEngagementTime: 'Wednesday at 12:00 PM',
        mostActiveHours: [
          { hour: '12:00 PM', activity: 95 },
          { hour: '11:00 AM', activity: 88 },
          { hour: '1:00 PM', activity: 84 },
          { hour: '9:00 AM', activity: 79 },
          { hour: '4:00 PM', activity: 72 },
        ],
        mostActiveDays: [
          { day: 'Wednesday', percentage: 18 },
          { day: 'Monday', percentage: 17 },
          { day: 'Tuesday', percentage: 16 },
        ],
        dailyActivity: [
          { day: 'Monday', activity: 17 },
          { day: 'Tuesday', activity: 16 },
          { day: 'Wednesday', activity: 18 },
          { day: 'Thursday', activity: 15 },
          { day: 'Friday', activity: 13 },
          { day: 'Saturday', activity: 9 },
          { day: 'Sunday', activity: 12 },
        ],
      },
      devices: { mobile: 65, desktop: 30, tablet: 4, smartTv: 1 },
      geography: {
        countries: [
          { name: 'United States', type: 'Country', percentage: 32, region: 'North America' },
          { name: 'India', type: 'Country', percentage: 15, region: 'Asia' },
          { name: 'United Kingdom', type: 'Country', percentage: 11, region: 'Europe' },
          { name: 'Germany', type: 'Country', percentage: 7, region: 'Europe' },
          { name: 'Canada', type: 'Country', percentage: 6, region: 'North America' },
          { name: 'Other Countries', type: 'Country', percentage: 29, region: 'Global' },
        ],
        regions: [
          { name: 'North America', type: 'Region', percentage: 41, region: 'North America' },
          { name: 'Europe', type: 'Region', percentage: 26, region: 'Europe' },
          { name: 'Asia', type: 'Region', percentage: 20, region: 'Asia' },
          { name: 'Middle East', type: 'Region', percentage: 7, region: 'Middle East' },
          { name: 'Other Regions', type: 'Region', percentage: 6, region: 'Global' },
        ],
        topCities: [
          { name: 'New York', type: 'City', percentage: 4, region: 'United States' },
          { name: 'San Francisco', type: 'City', percentage: 3, region: 'United States' },
          { name: 'London', type: 'City', percentage: 3, region: 'United Kingdom' },
          { name: 'Mumbai', type: 'City', percentage: 3, region: 'India' },
          { name: 'Toronto', type: 'City', percentage: 2, region: 'Canada' },
        ],
      },
      reach: {
        totalReach: 96000,
        totalImpressions: 480000,
        uniqueViewers: 61000,
        reachTrend: [
          { date: 'Mar', reach: 72000 },
          { date: 'Apr', reach: 77000 },
          { date: 'May', reach: 82000 },
          { date: 'Jun', reach: 86000 },
          { date: 'Jul', reach: 91000 },
          { date: 'Aug', reach: 96000 },
        ],
        impressionTrend: [
          { date: 'Mar', impressions: 360000 },
          { date: 'Apr', impressions: 390000 },
          { date: 'May', impressions: 420000 },
          { date: 'Jun', impressions: 440000 },
          { date: 'Jul', impressions: 460000 },
          { date: 'Aug', impressions: 480000 },
        ],
        watchTimeTrend: [
          { date: 'Mar', minutes: 12500 },
          { date: 'Apr', minutes: 14800 },
          { date: 'May', minutes: 17200 },
          { date: 'Jun', minutes: 19500 },
          { date: 'Jul', minutes: 21800 },
          { date: 'Aug', minutes: 24450 },
        ],
      },
      engagement: {
        totalLikes: 10930,
        totalComments: 1480,
        shares: 2450,
        saves: 1710,
        engagementRate: 3.5,
        trends: [
          { date: 'Mar', likes: 7900, comments: 1050, shares: 1750, saves: 1210 },
          { date: 'Apr', likes: 8600, comments: 1130, shares: 1900, saves: 1320 },
          { date: 'May', likes: 9300, comments: 1220, shares: 2050, saves: 1430 },
          { date: 'Jun', likes: 9900, comments: 1310, shares: 2200, saves: 1540 },
          { date: 'Jul', likes: 10500, comments: 1410, shares: 2350, saves: 1640 },
          { date: 'Aug', likes: 10930, comments: 1480, shares: 2450, saves: 1710 },
        ],
      },
    },
  },
  twitter: {
    account: {
      name: "Indie Creator Hub",
      handle: "@indie_creator",
      avatarUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150",
      bannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800",
      followersCount: 78000,
      followingCount: 620,
      contentCount: 5,
      totalViews: 145500,
      description: "Daily tips, threads, and honest breakdowns of the modern creator economy. Building in public since day one.",
      country: "Global",
      accountType: "USER",
      externalUrl: "https://x.com/indie_creator",
    },
    content: [
      {
        id: "tw_post_1",
        title: "10 lessons from growing to 100k subscribers in 1 year 🧵",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1557200134-90327ee9fafa?w=300",
        url: "https://x.com/indie_creator/status/demo1",
        publishedAt: "2026-08-14T08:30:00Z",
        metrics: {
          views: 42000,
          likes: 4800,
          comments: 620,
          shares: 1400,
          saves: 150,
          duration: null,
          watchTimeMinutes: 10500,
          reach: 85000,
        },
      },
      {
        id: "tw_post_2",
        title: "The secret to high engagement isn't luck, it's consistency.",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=300",
        url: "https://x.com/indie_creator/status/demo2",
        publishedAt: "2026-08-10T11:45:00Z",
        metrics: {
          views: 28000,
          likes: 3100,
          comments: 380,
          shares: 890,
          saves: 90,
          duration: null,
          watchTimeMinutes: 7200,
          reach: 56000,
        },
      },
      {
        id: "tw_post_3",
        title: "Hot take: most creators over-optimize for reach, not retention.",
        type: "post",
        thumbnailUrl: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=300",
        url: "https://x.com/indie_creator/status/demo3",
        publishedAt: "2026-08-06T14:10:00Z",
        metrics: {
          views: 19200,
          likes: 2300,
          comments: 310,
          shares: 760,
          saves: 120,
          duration: null,
          watchTimeMinutes: 4800,
          reach: 38000,
        },
      },
      {
        id: "tw_post_4",
        title: "Here is the exact 30-day content calendar I use:",
        type: "thread",
        thumbnailUrl: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=300",
        url: "https://x.com/indie_creator/status/demo4",
        publishedAt: "2026-07-30T07:50:00Z",
        metrics: {
          views: 31500,
          likes: 3900,
          comments: 460,
          shares: 1150,
          saves: 210,
          duration: null,
          watchTimeMinutes: 8100,
          reach: 63000,
        },
      },
      {
        id: "tw_post_5",
        title: "New milestone: 75,000 followers. Breakdown of what worked:",
        type: "thread",
        thumbnailUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=300",
        url: "https://x.com/indie_creator/status/demo5",
        publishedAt: "2026-07-24T19:30:00Z",
        metrics: {
          views: 24800,
          likes: 3400,
          comments: 410,
          shares: 980,
          saves: 160,
          duration: null,
          watchTimeMinutes: 6200,
          reach: 49000,
        },
      },
    ],
    // Twitter/X audience dataset — shaped like a science/tech voice (NASA-style):
    // young-male skew, mobile-heavy, active early mornings and evenings.
    audience: {
      overview: {
        totalFollowers: 78000,
        newFollowers: 2100,
        monthlyFollowerGrowth: 2.8,
        reach: 238000,
        impressions: 610000,
        avgEngagementRate: 4.2,
      },
      demographics: {
        age: [
          { range: '18-24', percentage: 22 },
          { range: '25-34', percentage: 35 },
          { range: '35-44', percentage: 24 },
          { range: '45-54', percentage: 12 },
          { range: '55+', percentage: 7 },
        ],
        gender: [
          { label: 'Male', percentage: 61 },
          { label: 'Female', percentage: 36 },
          { label: 'Other', percentage: 3 },
        ],
        countries: [
          { name: 'United States', percentage: 30, region: 'North America' },
          { name: 'India', percentage: 13, region: 'Asia' },
          { name: 'Japan', percentage: 9, region: 'Asia' },
          { name: 'United Kingdom', percentage: 8, region: 'Europe' },
          { name: 'Brazil', percentage: 6, region: 'South America' },
          { name: 'Other Countries', percentage: 34, region: 'Global' },
        ],
        regions: [
          { name: 'North America', percentage: 38 },
          { name: 'Asia', percentage: 26 },
          { name: 'Europe', percentage: 20 },
          { name: 'South America', percentage: 8 },
          { name: 'Other Regions', percentage: 8 },
        ],
        topCities: [
          { name: 'New York', country: 'United States', percentage: 4 },
          { name: 'Washington DC', country: 'United States', percentage: 3 },
          { name: 'London', country: 'United Kingdom', percentage: 3 },
          { name: 'Tokyo', country: 'Japan', percentage: 3 },
          { name: 'Mumbai', country: 'India', percentage: 2 },
        ],
      },
      followerGrowth: {
        daily: 70,
        weekly: 490,
        monthly: 2100,
        total: 78000,
        newFollowers: 2100,
        growthPercentage: 2.8,
        timeline: [
          { date: 'Mar', followers: 64000, newFollowers: 1800 },
          { date: 'Apr', followers: 66800, newFollowers: 2800 },
          { date: 'May', followers: 69500, newFollowers: 2700 },
          { date: 'Jun', followers: 72100, newFollowers: 2600 },
          { date: 'Jul', followers: 75200, newFollowers: 3100 },
          { date: 'Aug', followers: 78000, newFollowers: 2800 },
        ],
      },
      activity: {
        peakEngagementTime: 'Wednesday at 6:00 PM',
        mostActiveHours: [
          { hour: '6:00 PM', activity: 91 },
          { hour: '7:00 PM', activity: 87 },
          { hour: '8:00 AM', activity: 82 },
          { hour: '5:00 PM', activity: 78 },
          { hour: '9:00 PM', activity: 72 },
        ],
        mostActiveDays: [
          { day: 'Wednesday', percentage: 16 },
          { day: 'Friday', percentage: 15 },
          { day: 'Monday', percentage: 14 },
        ],
        dailyActivity: [
          { day: 'Monday', activity: 14 },
          { day: 'Tuesday', activity: 14 },
          { day: 'Wednesday', activity: 16 },
          { day: 'Thursday', activity: 15 },
          { day: 'Friday', activity: 15 },
          { day: 'Saturday', activity: 13 },
          { day: 'Sunday', activity: 13 },
        ],
      },
      devices: { mobile: 82, desktop: 15, tablet: 2, smartTv: 1 },
      geography: {
        countries: [
          { name: 'United States', type: 'Country', percentage: 30, region: 'North America' },
          { name: 'India', type: 'Country', percentage: 13, region: 'Asia' },
          { name: 'Japan', type: 'Country', percentage: 9, region: 'Asia' },
          { name: 'United Kingdom', type: 'Country', percentage: 8, region: 'Europe' },
          { name: 'Brazil', type: 'Country', percentage: 6, region: 'South America' },
          { name: 'Other Countries', type: 'Country', percentage: 34, region: 'Global' },
        ],
        regions: [
          { name: 'North America', type: 'Region', percentage: 38, region: 'North America' },
          { name: 'Asia', type: 'Region', percentage: 26, region: 'Asia' },
          { name: 'Europe', type: 'Region', percentage: 20, region: 'Europe' },
          { name: 'South America', type: 'Region', percentage: 8, region: 'South America' },
          { name: 'Other Regions', type: 'Region', percentage: 8, region: 'Global' },
        ],
        topCities: [
          { name: 'New York', type: 'City', percentage: 4, region: 'United States' },
          { name: 'Washington DC', type: 'City', percentage: 3, region: 'United States' },
          { name: 'London', type: 'City', percentage: 3, region: 'United Kingdom' },
          { name: 'Tokyo', type: 'City', percentage: 3, region: 'Japan' },
          { name: 'Mumbai', type: 'City', percentage: 2, region: 'India' },
        ],
      },
      reach: {
        totalReach: 238000,
        totalImpressions: 610000,
        uniqueViewers: 142000,
        reachTrend: [
          { date: 'Mar', reach: 184000 },
          { date: 'Apr', reach: 199000 },
          { date: 'May', reach: 211000 },
          { date: 'Jun', reach: 220000 },
          { date: 'Jul', reach: 230000 },
          { date: 'Aug', reach: 238000 },
        ],
        impressionTrend: [
          { date: 'Mar', impressions: 470000 },
          { date: 'Apr', impressions: 510000 },
          { date: 'May', impressions: 540000 },
          { date: 'Jun', impressions: 565000 },
          { date: 'Jul', impressions: 588000 },
          { date: 'Aug', impressions: 610000 },
        ],
        watchTimeTrend: [
          { date: 'Mar', minutes: 28500 },
          { date: 'Apr', minutes: 31200 },
          { date: 'May', minutes: 33800 },
          { date: 'Jun', minutes: 35800 },
          { date: 'Jul', minutes: 37200 },
          { date: 'Aug', minutes: 36800 },
        ],
      },
      engagement: {
        totalLikes: 17500,
        totalComments: 2180,
        shares: 5180,
        saves: 730,
        engagementRate: 4.2,
        trends: [
          { date: 'Mar', likes: 11800, comments: 1450, shares: 3400, saves: 480 },
          { date: 'Apr', likes: 13100, comments: 1620, shares: 3800, saves: 540 },
          { date: 'May', likes: 14200, comments: 1750, shares: 4100, saves: 590 },
          { date: 'Jun', likes: 15400, comments: 1900, shares: 4450, saves: 640 },
          { date: 'Jul', likes: 16600, comments: 2050, shares: 4850, saves: 690 },
          { date: 'Aug', likes: 17500, comments: 2180, shares: 5180, saves: 730 },
        ],
      },
    },
  },
};
