"""Add device_type column to users

Revision ID: 26a5215e7004
Revises: 77cf3d1b5930
Create Date: 2026-07-20 14:22:41.604520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a5215e7004'
down_revision: Union[str, Sequence[str], None] = '77cf3d1b5930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_type')
    # ### end Alembic commands ###
