import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Real PDF report generation for the Reports page.
 *
 * Produces a professional, printable .pdf built ONLY from the active platform
 * dataset (metrics / videos / audience) that is passed in — the same data used
 * by the on-screen report. The generated bytes are used both for the browser
 * download and for the email attachment sent by the backend.
 */

const fmtCompact = (n) => {
  if (n == null || Number.isNaN(Number(n))) return '—';
  const v = Number(n);
  if (v >= 1000000) return `${(v / 1000000).toFixed(1)}M`;
  if (v >= 1000) return `${(v / 1000).toFixed(1)}K`;
  return String(Math.round(v));
};
const fmtNum = (n) => (n == null || Number.isNaN(Number(n)) ? '—' : Number(n).toLocaleString());
const fmtMoney = (n) => (n == null || Number.isNaN(Number(n)) ? '—' : `$${Number(n).toLocaleString()}`);

export function reportFileName(platform, reportType, ext) {
  const slug = (reportType || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '_');
  return `creatoriq_${platform || 'report'}_${slug}.${ext}`;
}

/**
 * Build a PDF Blob for the active platform dataset.
 */
export function buildReportPdfBlob({
  accountTitle,
  platformName,
  reportType,
  reportPeriod,
  generatedAt,
  metrics,
  videos,
  audience,
}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;

  const header = () => {
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageW, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(17);
    doc.text('CreatorIQ — Performance Report', margin, 13);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(203, 213, 225);
    doc.text(`${platformName || 'Active Platform'} · ${accountTitle || 'Account'}`, margin, 20);
    doc.setFontSize(9);
    doc.text(
      `${reportType || 'Report'} · ${reportPeriod || 'Current Period'} · Generated ${new Date(generatedAt || Date.now()).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })}`,
      margin,
      26,
    );
  };

  const footer = () => {
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i += 1) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(148, 163, 184);
      doc.text(`CreatorIQ · Generated by CreatorIQ on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`, margin, pageH - 8);
      doc.text(`Page ${i} of ${pages}`, pageW - margin, pageH - 8, { align: 'right' });
    }
  };

  const sectionTitle = (y, text) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(text, margin, y);
    doc.setDrawColor(79, 70, 229);
    doc.setLineWidth(0.6);
    doc.line(margin, y + 1.5, margin + 18, y + 1.5);
    return y + 6;
  };

  header();

  // ── KPI cards ────────────────────────────────────────────────────────
  const kpis = [
    { label: 'Total Views', value: fmtCompact(metrics?.aggregateViews), sub: fmtNum(metrics?.aggregateViews) },
    { label: `${metrics?.followerLabel || 'Followers'}`, value: fmtCompact(metrics?.followers), sub: fmtNum(metrics?.followers) },
    { label: 'Engagement Rate', value: `${metrics?.engagementRate ?? 0}%`, sub: `${fmtNum(metrics?.totalLikes)} likes · ${fmtNum(metrics?.totalComments)} comments` },
    { label: 'Revenue (Current Month)', value: fmtMoney(metrics?.currentMonthRev), sub: `${fmtMoney(metrics?.totalRevenue)} all-time` },
  ];
  const cardW = (pageW - margin * 2 - 8) / 4;
  const cardH = 22;
  doc.setFont('helvetica', 'normal');
  kpis.forEach((k, i) => {
    const x = margin + i * (cardW + 2);
    const y = 36;
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(x, y, cardW, cardH, 2, 2, 'F');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(k.label.toUpperCase(), x + 3, y + 6);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(k.value, x + 3, y + 13);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(148, 163, 184);
    doc.text(k.sub, x + 3, y + 19, { maxWidth: cardW - 4 });
  });

  // ── Analytics Summary ────────────────────────────────────────────────
  let y = sectionTitle(64, 'Analytics Summary');
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Metric', 'Value']],
    body: [
      ['Total Views', fmtNum(metrics?.aggregateViews)],
      ['New Followers', fmtNum(metrics?.newFollowers)],
      ['Audience Reach', fmtNum(metrics?.reach)],
      ['Impressions', fmtNum(metrics?.impressions)],
      ['Watch Time', `${fmtNum(metrics?.watchTimeHours)} hours`],
      ['Total Revenue (All Streams)', fmtMoney(metrics?.totalRevenue)],
      ['Month-over-Month Growth', `${metrics?.growthPct ?? 0}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5, textColor: [51, 65, 85] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { cellPadding: 2.4 },
    columnStyles: { 0: { cellWidth: 60 }, 1: { cellWidth: 'auto' } },
  });

  // ── Revenue Breakdown ────────────────────────────────────────────────
  const sources = metrics?.sources || [];
  if (sources.length > 0) {
    y = sectionTitle(doc.lastAutoTable.finalY + 8, 'Revenue Breakdown');
    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Revenue Stream', 'Amount (USD)']],
      body: sources.map((s) => [s.name, fmtMoney(s.amount)]),
      theme: 'grid',
      headStyles: { fillColor: [5, 150, 105], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
      bodyStyles: { fontSize: 8.5, textColor: [51, 65, 85] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { cellPadding: 2.4 },
      columnStyles: { 0: { cellWidth: 110 }, 1: { cellWidth: 'auto' } },
    });
  }

  // ── Content Performance ──────────────────────────────────────────────
  const topContent = (videos || []).slice().sort((a, b) => (b.views || 0) - (a.views || 0)).slice(0, 12);
  if (topContent.length > 0) {
    y = sectionTitle(doc.lastAutoTable.finalY + 8, 'Content Performance (Top)');
    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Content Title', 'Published', 'Views', 'Likes', 'Comments', 'Eng. Rate']],
      body: topContent.map((v) => {
        const likes = v.likes || 0;
        const comments = v.comments || 0;
        const eng = metrics?.followers > 0 ? `${(((likes + comments) / metrics.followers) * 100).toFixed(2)}%` : '—';
        return [
          v.title || 'Untitled',
          v.published_at ? new Date(v.published_at).toISOString().slice(0, 10) : '—',
          fmtNum(v.views),
          fmtNum(v.likes),
          fmtNum(v.comments),
          eng,
        ];
      }),
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
      bodyStyles: { fontSize: 8, textColor: [51, 65, 85] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { cellPadding: 2.2 },
      columnStyles: {
        0: { cellWidth: 70 },
        1: { cellWidth: 22 },
        2: { cellWidth: 20 },
        3: { cellWidth: 18 },
        4: { cellWidth: 20 },
        5: { cellWidth: 'auto' },
      },
    });
  }

  // ── Growth Overview ──────────────────────────────────────────────────
  const timeline = audience?.followerGrowth?.timeline || [];
  if (timeline.length > 0) {
    const totalNew = timeline.reduce((acc, m) => acc + (m.newFollowers || 0), 0) || 1;
    y = sectionTitle(doc.lastAutoTable.finalY + 8, 'Growth Overview');
    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Period', 'Followers', 'New Followers', 'Views', 'Revenue']],
      body: timeline.map((m) => {
        const weight = metrics?.followers > 0 ? (m.followers || 0) / metrics.followers : 0;
        const views = Math.round((metrics?.aggregateViews || 0) * weight);
        const revenue = Math.round((metrics?.totalRevenue || 0) * ((m.newFollowers || 0) / totalNew));
        return [m.date, fmtNum(m.followers), `+${fmtNum(m.newFollowers || 0)}`, fmtNum(views), fmtMoney(revenue)];
      }),
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
      bodyStyles: { fontSize: 8.5, textColor: [51, 65, 85] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { cellPadding: 2.4 },
    });
  }

  // ── Audience Snapshot ────────────────────────────────────────────────
  const dem = audience?.demographics || {};
  const snapshot = [
    ['Top Age Group', dem.age?.[0] ? `${dem.age[0].range} (${dem.age[0].percentage}%)` : '—'],
    ['Top Country', dem.countries?.[0] ? `${dem.countries[0].name} (${dem.countries[0].percentage}%)` : '—'],
    ['Top City', dem.topCities?.[0] ? `${dem.topCities[0].name} (${dem.topCities[0].percentage}%)` : '—'],
    ['Mobile Devices', `${audience?.devices?.mobile ?? '—'}%`],
    ['Desktop Devices', `${audience?.devices?.desktop ?? '—'}%`],
  ];
  y = sectionTitle(doc.lastAutoTable.finalY + 8, 'Audience Snapshot');
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Metric', 'Value']],
    body: snapshot,
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5, textColor: [51, 65, 85] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { cellPadding: 2.4 },
    columnStyles: { 0: { cellWidth: 60 }, 1: { cellWidth: 'auto' } },
  });

  footer();
  return doc.output('blob');
}

/**
 * Trigger a browser download of the report PDF.
 */
export function downloadReportPdf({ accountTitle, platformName, reportType, reportPeriod, metrics, videos, audience, platform }) {
  const blob = buildReportPdfBlob({
    accountTitle,
    platformName,
    reportType,
    reportPeriod,
    metrics,
    videos,
    audience,
  });
  const fileName = reportFileName(platform, reportType, 'pdf');
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
  return { blob, fileName };
}
